### PR TITLE
Issue #2644482 by donquixote: support PHP7 via alcaeus/mongo-php-adapter

### PR DESCRIPTION
**Pull request by fgm**
https://www.drupal.org/project/mongodb/issues/2644482#comment-12680467

### CODE REVIEW

**Comment by donquixote** [comment]
So we play on github now? Great!

If we are already here, I would suggest to split the commits up, so that code style fixes are separated from functional changes, and every commit has a meaningful commit message.

From the drupal.org issue:

> For some reason, xautoload 7.x-5.7 doesn't succesfully autoload the alcaeus classes, even when registering the composerDir()

If you want help with this, feel free to PM me or open an issue in the xautoload queue. I would need to see what exactly you are trying to do.

One thing to note with xautoload is that many methods in the hook accept paths relative to the module directory. The second parameter needs to be used to make those paths absolute, or relative to project root (don't remember exactly, but it is documented on each method).

> so I just relied the Composer autoloader, explaining how to do it in the README.

I think there are a few different strategies out there for composer integration in D7. The choice is made per project / website.

- composer_manager is suitable for projects that started without composer integration, and allows to add Composer libraries without restructuring the project itself.
- some new D7 projects install everything, including Drupal core itself and all contrib modules, with Composer.
- It seems you are proposing something else, not sure exactly how that would look like.
- xautoload can help you with class loading, but not with package management or dependency management. And it needs to know where your class files are, obviously. I usually don't use xautoload for this purpose, even though it is "my baby".

**Comment by fgm** [comment]
Basically, in the last 5 years or so, I built all my D7 and D8 projects pretty much like drupal-composer/drupal-project, with a project root containing the composer files and vendor/, the logs, tmpdir, privatedir, settings, etc, and just adding a require_once '../vendor/autoload.php' to load all the composer dependencies, and building the non-drupal project dependencies entirely with composer and npm/yarn, not drush make, even for D7 (actually also converted my legacy D6 projects to it).

With this approach, just requiring drupal/mongodb and mongodb/mongodb is sufficient to have autoload working. In the case of this issue, I tried to use xautoload because it is less exotic than the approach above but it wouldn't load the \MongoClient class from ../vendor/alcaeus/mongodb-php-adapter, although the files are actually present in ../vendor/composer/autoload_*, but it doesn't matter since the composer autoloader does the job well enough, although it is probably less optimized.

**Comment by fgm** [comment]
Actually, I think that for visibility's sake, it's better if we keep the discussion on d.o., and just use github for the PRs and line comments à la dreditor, don't you think ?

**Comment by donquixote** [comment]
> Actually, I think that for visibility's sake, it's better if we keep the discussion on d.o., and just use github for the PRs and line comments à la dreditor, don't you think ?

You are right, community visibility is better on drupal.org.

**Pull request merged**
